### ISSUE TITLE
running SIPserver as a service

### ISSUE THREAD

**Issue by SensorsIot** [BarGabriel/SipServer#8]
We would like to run SIPserver as a service on our Mikrotik openWRT routers. It is already cross-compiled and runs, but not as a service with an automatic restart.

**Comment by finfinack** [comment]
Specifically, I think the problem we're running into is that once the server started listening, it waits for input on stdin and if it gets anything it just quits:

```
		std::string ip = result["ip"].as<std::string>();
		int port = result["port"].as<int>();
		SipServer server(std::move(ip), port);
		std::cout << "Server has been started. Listening..." << std::endl;
		getchar();
```

Any chance, you can modify it such that it can be daemonized? I would assume listening specifically for a CTRL-C / `SIGINT` instead of any char might even do the trick to start with?

**Comment by finfinack** [comment]
I played with this for a bit and I think I have a working solution (compiled, ran on Linux locally, compiled in OpenWrt and ran fine in our planned environment). PR: https://github.com/BarGabriel/SipServer/pull/9

**Comment by BarGabriel** [comment]
Hi, thanks for reaching out.
Currently, the project is not supported with running as a service.

I think it's more complex than listening to a specific signal becuase as far as I know in order to run a program as a service, at least in Windows, its requires including windows api and follow a specific pattern that the program need to support.

In Linux, it seems that it will works for your needs, I think that using getchar() can make some troubles in order to do so, as you described above.

Sorry but currently i'm not working on this project, good luck!
